[project]
name = "toweroffantasy.api"
version = "2.0.0"
description = "Made from players to players"
authors = [
    { name = "Gabriel Nobrega", email = "gabrieltkdnobrega63@gmail.com" },
]
dependencies = [
    "pydantic>=2.6.1",
    "fastapi>=0.109.2",
    "pytz>=2024.1",
    "uvicorn>=0.27.1",
    "pyyaml>=6.0.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "All Rights Reserved" }


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = ["types-pytz>=2024.1.0.20240203"]

[tool.pdm.scripts]
prod = "uvicorn src.main.app:app --no-access-log --log-config ./log-config.yml"
dev = "uvicorn src.main.app:app --reload --reload-dir ./ --log-config ./log-config.yml"
