name: Deploy

on:
  push:
    branches: [v3]

jobs:
  publish-main:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            cd code && docker compose up -d api --build
