name: Deploy

on:
  push:
    branches: [v3]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            cd code && docker compose up -d --build
          debug: true
