on:
  push:
    branches:
      - main

jobs:
  job:
    name: testing deploy
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: pip install -r requirements.txt
    steps:
      - name: API init
        run: python main.py
